### PR TITLE
allow swapping the environment and repo names in the lock and unlock commands

### PR DESCRIPTION
**Pull request by emi-wheee**

### CODE REVIEW

**Comment by isobit** [comment]
I like the idea of tolerating the reversal since grammatically it works either way, but I feel uncomfortable about making the slashdeploy command parsing even more ambiguous. This has the potential to be dangerous if someone were to have a repo with the same name as an environment.

**Comment by emi-wheee** [comment]
Would you feel better about just reversing the order of them and not allowing both? Honestly my main complaint is the inconsistency between deploy ("project on environment") and lock ("environment on project"); I did it this way because I figured a lot of people who have been using this longer than I have will have the backwards way committed to muscle memory by now.

**Comment by aengelas** [comment]
I'm +1 on @emi-wheee 's idea to just standardize the order.

**Comment by jherico** [comment]
why don't we make repositories of `production` and `staging` right now and just put readmes in them explaining they should never be used for apps and why.

Quality of life is king, and not having to remember argument order sparks joy.

**Comment by aengelas** [comment]
Or maybe even better, just use flags instead of positional arguments. then it's choose your ordering adventure

**Comment by aengelas** [comment]
Closing this since we're getting rid of slashdeploy.

**Pull request closed without merging**
